

export const categories = [
    {name : "Afghanistan",  type : 'category'},
    {name : "Albania",  type : 'category'},
    {name : 'Algeria',  type : 'category'},
    {name : 'Andorra',  type : 'category'},
    {name : 'Angola',  type : 'category'},
    {name : 'Antigua',  type : 'category'},
    {name : 'Argentina',  type : 'category'},
    {name : 'Armenia',  type : 'category'},
    {name : 'Australia',  type : 'category'},
    {name : 'Austria',  type : 'category'},
    {name : 'Austrian Empire',  type : 'category'},
    {name : 'Azerbaijan',  type : 'category'},
    {name : 'Baden',  type : 'category'},
    {name : 'Bahamas',  type : 'category'},
    {name : 'Bahrain',  type : 'category'},
    {name : 'Bangladesh',  type : 'category'},
    {name : 'Bavaria',  type : 'category'},
    {name : 'Belarus',  type : 'category'},
    {name : 'Belgium',  type : 'category'},
    {name : 'Belize',  type : 'category'},
    {name : 'Benin (Dahomey)',  type : 'category'},
    {name : 'Bolivia',  type : 'category'},
    {name : 'Bosnia and Herzegovina',  type : 'category'},
    {name : 'Botswana',  type : 'category'},
    {name : 'Brazil',  type : 'category'},
    {name : 'Brunei',  type : 'category'},
    {name : 'Brunswick and Lüneburg',  type : 'category'},
    {name : 'Bulgaria',  type : 'category'},
    {name : 'Burkina Faso (Upper Volta)',  type : 'category'},
    {name : 'Burma',  type : 'category'},
    {name : 'Burundi',  type : 'category'},
    {name : 'Cabo Verde',  type : 'category'},
    {name : 'Cambodia',  type : 'category'},
    {name : 'Cameroon',  type : 'category'},
    {name : 'Canada',  type : 'category'},
    {name : 'Cayman Islands, The',  type : 'category'},
    {name : 'Central African Republic',  type : 'category'},
    {name : 'Central American Federation*',  type : 'category'},
    {name : 'Chad',  type : 'category'},
    {name : 'Chile',  type : 'category'},
    {name : 'China',  type : 'category'},
    {name : 'Colombia',  type : 'category'},
    {name : 'Comoros',  type : 'category'},
    {name : 'Congo Free State, The*',  type : 'category'},
    {name : 'Costa Rica',  type : 'category'},
    {name : 'Cote d’Ivoire (Ivory Coast)',  type : 'category'},
    {name : 'Croatia',  type : 'category'},
    {name : 'Cuba',  type : 'category'},
    {name : 'Cyprus',  type : 'category'},
    {name : 'Czechia',  type : 'category'},
    {name : 'Czechoslovakia',  type : 'category'},
    {name : 'Democratic Republic of the Congo',  type : 'category'},
    {name : 'Denmark',  type : 'category'},
    {name : 'Djibouti',  type : 'category'},
    {name : 'Dominica',  type : 'category'},
    {name : 'Dominican Republic',  type : 'category'},
    {name : 'Duchy of Parma, The',  type : 'category'},
    {name : 'East Germany (German Democratic Republic)*',  type : 'category'},
    {name : 'Ecuador',  type : 'category'},
    {name : 'Egypt',  type : 'category'},
    {name : 'El Salvador',  type : 'category'},
    {name : 'Equatorial Guinea',  type : 'category'},
    {name : 'Eritrea',  type : 'category'},
    {name : 'Estonia',  type : 'category'},
    {name : 'Eswatini',  type : 'category'},
    {name : 'Ethiopia',  type : 'category'},
    {name : 'Federal Government of Germany (1848-49)',  type : 'category'},
    {name : 'Fiji',  type : 'category'},
    {name : 'Finland',  type : 'category'},
    {name : 'France',  type : 'category'},
    {name : 'Gabon',  type : 'category'},
    {name : 'Gambia, The',  type : 'category'},
    {name : 'Georgia',  type : 'category'},
    {name : 'Germany',  type : 'category'},
    {name : 'Ghana',  type : 'category'},
    {name : 'Grand Duchy of Tuscany, The*',  type : 'category'},
    {name : 'Greece',  type : 'category'},
    {name : 'Grenada',  type : 'category'},
    {name : 'Guatemala',  type : 'category'},
    {name : 'Guinea',  type : 'category'},
    {name : 'Guinea-Bissau',  type : 'category'},
    {name : 'Guyana',  type : 'category'},
    {name : 'Haiti',  type : 'category'},
    {name : 'Hanover*',  type : 'category'},
    {name : 'Hanseatic Republics*',  type : 'category'},
    {name : 'Hawaii*',  type : 'category'},
    {name : 'Hesse*',  type : 'category'},
    {name : 'Holy See',  type : 'category'},
    {name : 'Honduras',  type : 'category'},
    {name : 'Hungary',  type : 'category'},
    {name : 'Iceland',  type : 'category'},
    {name : 'India',  type : 'category'},
    {name : 'Indonesia',  type : 'category'},
    {name : 'Iran',  type : 'category'},
    {name : 'Iraq',  type : 'category'},
    {name : 'Ireland',  type : 'category'},
    {name : 'Israel',  type : 'category'},
    {name : 'Italy',  type : 'category'},
    {name : 'Jamaica',  type : 'category'},
    {name : 'Japan',  type : 'category'},
    {name : 'Jordan',  type : 'category'},
    {name : 'Kazakhstan',  type : 'category'},
    {name : 'Kenya',  type : 'category'},
    {name : 'Kingdom of Serbia/Yugoslavia',  type : 'category'},
    {name : 'Kiribati',  type : 'category'},
    {name : 'Korea',  type : 'category'},
    {name : 'Kosovo',  type : 'category'},
    {name : 'Kuwait',  type : 'category'},
    {name : 'Kyrgyzstan',  type : 'category'},
    {name : 'Laos',  type : 'category'},
    {name : 'Latvia',  type : 'category'},
    {name : 'Lebanon',  type : 'category'},
    {name : 'Lesotho',  type : 'category'},
    {name : 'Lew Chew (Loochoo)',  type : 'category'},
    {name : 'Liberia',  type : 'category'},
    {name : 'Libya',  type : 'category'},
    {name : 'Liechtenstein',  type : 'category'},
    {name : 'Lithuania',  type : 'category'},
    {name : 'Luxembourg',  type : 'category'},
    {name : 'Madagascar',  type : 'category'},
    {name : 'Malawi',  type : 'category'},
    {name : 'Malaysia',  type : 'category'},
    {name : 'Maldives',  type : 'category'},
    {name : 'Mali',  type : 'category'},
    {name : 'Malta',  type : 'category'},
    {name : 'Marshall Islands',  type : 'category'},
    {name : 'Mauritania',  type : 'category'},
    {name : 'Mauritius',  type : 'category'},
    {name : 'Mecklenburg-Schwerin',  type : 'category'},
    {name : 'Mecklenburg-Strelitz',  type : 'category'},
    {name : 'Mexico',  type : 'category'},
    {name : 'Micronesia',  type : 'category'},
    {name : 'Moldova',  type : 'category'},
    {name : 'Monaco',  type : 'category'},
    {name : 'Mongolia',  type : 'category'},
    {name : 'Montenegro',  type : 'category'},
    {name : 'Morocco',  type : 'category'},
    {name : 'Mozambique',  type : 'category'},
    {name : 'Namibia',  type : 'category'},
    {name : 'Nassau*',  type : 'category'},
    {name : 'Nauru',  type : 'category'},
    {name : 'Nepal',  type : 'category'},
    {name : 'Netherlands, The',  type : 'category'},
    {name : 'New Zealand',  type : 'category'},
    {name : 'Nicaragua',  type : 'category'},
    {name : 'Niger',  type : 'category'},
    {name : 'Nigeria',  type : 'category'},
    {name : 'North German Confederation*',  type : 'category'},
    {name : 'North German Union*',  type : 'category'},
    {name : 'North Macedonia',  type : 'category'},
    {name : 'Norway',  type : 'category'},
    {name : 'Oldenburg*',  type : 'category'},
    {name : 'Oman',  type : 'category'},
    {name : 'Orange Free State',  type : 'category'},
    {name : 'Pakistan',  type : 'category'},
    {name : 'Palau',  type : 'category'},
    {name : 'Panama',  type : 'category'},
    {name : 'Papal States*',  type : 'category'},
    {name : 'Papua New Guinea',  type : 'category'},
    {name : 'Paraguay',  type : 'category'},
    {name : 'Peru',  type : 'category'},
    {name : 'Philippines',  type : 'category'},
    {name : 'Piedmont-Sardinia',  type : 'category'},
    {name : 'Poland',  type : 'category'},
    {name : 'Portugal',  type : 'category'},
    {name : 'Qatar',  type : 'category'},
    {name : 'Republic of Genoa',  type : 'category'},
    {name : 'Republic of Korea (South Korea)',  type : 'category'},
    {name : 'Republic of the Congo',  type : 'category'},
    {name : 'Romania',  type : 'category'},
    {name : 'Russia',  type : 'category'},
    {name : 'Rwanda',  type : 'category'},
    {name : 'Saint Kitts and Nevis',  type : 'category'},
    {name : 'Saint Lucia',  type : 'category'},
    {name : 'Saint Vincent and the Grenadines',  type : 'category'},
    {name : 'Samoa',  type : 'category'},
    {name : 'San Marino',  type : 'category'},
    {name : 'Sao Tome and Principe',  type : 'category'},
    {name : 'Saudi Arabia',  type : 'category'},
    {name : 'Schaumburg-Lippe*',  type : 'category'},
    {name : 'Senegal',  type : 'category'},
    {name : 'Serbia',  type : 'category'},
    {name : 'Seychelles',  type : 'category'},
    {name : 'Sierra Leone',  type : 'category'},
    {name : 'Singapore',  type : 'category'},
    {name : 'Slovakia',  type : 'category'},
    {name : 'Slovenia',  type : 'category'},
    {name : 'Solomon Islands, The',  type : 'category'},
    {name : 'Somalia',  type : 'category'},
    {name : 'South Africa',  type : 'category'},
    {name : 'South Sudan',  type : 'category'},
    {name : 'Spain',  type : 'category'},
    {name : 'Sri Lanka',  type : 'category'},
    {name : 'Sudan',  type : 'category'},
    {name : 'Suriname',  type : 'category'},
    {name : 'Sweden',  type : 'category'},
    {name : 'Switzerland',  type : 'category'},
    {name : 'Syria',  type : 'category'},
    {name : 'Tajikistan',  type : 'category'},
    {name : 'Tanzania',  type : 'category'},
    {name : 'Texas*',  type : 'category'},
    {name : 'Thailand',  type : 'category'},
    {name : 'Timor-Leste',  type : 'category'},
    {name : 'Togo',  type : 'category'},
    {name : 'Tonga',  type : 'category'},
    {name : 'Trinidad and Tobago',  type : 'category'},
    {name : 'Tunisia',  type : 'category'},
    {name : 'Turkey',  type : 'category'},
    {name : 'Turkmenistan',  type : 'category'},
    {name : 'Tuvalu',  type : 'category'},
    {name : 'Two Sicilies*',  type : 'category'},
    {name : 'Uganda',  type : 'category'},
    {name : 'Ukraine',  type : 'category'},
    {name : 'Union of Soviet Socialist Republics*',  type : 'category'},
    {name : 'United Arab Emirates, The',  type : 'category'},
    {name : 'United Kingdom, The',  type : 'category'},
    {name : 'Uruguay',  type : 'category'},
    {name : 'Uzbekistan',  type : 'category'},
    {name : 'Vanuatu',  type : 'category'},
    {name : 'Venezuela',  type : 'category'},
    {name : 'Vietnam',  type : 'category'},
    {name : 'Württemberg*',  type : 'category'},
    {name : 'Yemen',  type : 'category'},
    {name : 'Zambia',  type : 'category'},
    {name : 'Zimbabwe',  type : 'category'},

]
